spring.application.name=phase-03-data-access
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/practice}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:practice}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.locations=filesystem:../../../sql-practice/migrations
spring.jpa.show-sql=false
