/*
CHALLENGE 1: High-Volume Data Filtering & Indexing (Difficulty: Easy)
Scenario: The Operations team wants to investigate recently completed orders for a rolling monthly report.
Requirement: Write a query to retrieve all orders from the orders table where the order_status is 'COMPLETED' and 
the created_at timestamp is within the last 30 days (relative to the current date). Sort the results by total_price in descending order.

Performance Goal: * Step 1: Run the query on the raw table. Check the execution plan and note the time (Look out for a heavy Table Scan or Clustered Index Scan).

Step 2: Create a non-clustered index on order_status and created_at. Re-run the query. The execution time must drop under 15ms using an Index Seek.

CHALLENGE 2: Financial Data Reconciliation (Difficulty: Medium)
Scenario: The Auditing department suspects a system mismatch between the E-commerce checkout platform and the Core Banking ledger.

Requirement: Write a reconciliation query to detect data integrity issues. Find all orders with a 'COMPLETED' status where the total_price in the orders table does not match the payment amount recorded in the transactions table (linked via order_id).

Performance Goal: Avoid using complex mathematical transformations inside the JOIN predicate. Ensure the Query Optimizer utilizes a highly efficient Merge Join or Hash Match instead of a nested loop.

CHALLENGE 3: Customer Behavior Analytics (Difficulty: Hard)
Scenario: The Marketing team is launching a VIP loyalty program and needs to analyze historical high-value purchases.

Requirement: For each customer (account_id), find their Top 3 highest-valued orders based on total_price. The output must contain: account_id, order_id, total_price, and the rank of that order relative to the customer's purchase history.

Performance Goal: Do NOT use loops or correlated subqueries, as they will bottleneck on 1 million rows. Utilize Window Functions (DENSE_RANK() or ROW_NUMBER()) combined with PARTITION BY to allow SQL Server to compute ranks efficiently in-memory.

CHALLENGE 4: Real-time Credit Card Fraud Detection (Difficulty: Hard)
Scenario: The Risk Management system needs to flag accounts displaying rapid, automated transaction patterns (velocity checks).

Requirement: Identify all suspicious accounts (account_id) that have triggered 3 or more consecutive transactions within a time window of less than 15 minutes.

Performance Goal: This is a classic FAANG/Big Tech interview question. You must use analytic window functions like LAG() or LEAD() to compute the time delta between sequential transactions of the same account without resorting to a heavy self-join of the 1-million-row table.

🏋️ CHALLENGE 5: Category Revenue Contribution Report (Difficulty: Expert / Out-Of-Memory Challenge)
Scenario: The executive board requires an end-of-quarter business intelligence report regarding product performance.

Requirement: Generate a comprehensive report displaying: Product Name (product_name), Total Quantity Sold, Total Revenue Generated by that product, and the percentage (%) contribution of that product's revenue towards the TOTAL revenue of its entire Category.

Performance Goal: You are aggregating data at two different granularity levels (Product level vs. Category level) simultaneously over millions of records. Use a Common Table Expression (CTE) to isolate the category-level pre-aggregations, preventing SQL Server from spilling data to tempdb (disk) and keeping execution purely in RAM.
*/