-- Flyway canonical migration; SQL-01 and SQL-10 use this schema.
CREATE TABLE accounts (
    account_id varchar(50) PRIMARY KEY,
    customer_name varchar(100) NOT NULL,
    account_type varchar(20) NOT NULL CHECK (account_type IN ('SAVINGS', 'CHECKING', 'CREDIT')),
    balance numeric(15, 2) NOT NULL CHECK (balance >= 0),
    created_at timestamptz NOT NULL
);

CREATE TABLE products (
    product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name varchar(150) NOT NULL UNIQUE,
    category varchar(50) NOT NULL,
    price numeric(12, 2) NOT NULL CHECK (price >= 0),
    stock_quantity integer NOT NULL CHECK (stock_quantity >= 0)
);

CREATE TABLE orders (
    order_id varchar(50) PRIMARY KEY,
    account_id varchar(50) NOT NULL REFERENCES accounts(account_id),
    total_price numeric(15, 2) NOT NULL CHECK (total_price >= 0),
    order_status varchar(20) NOT NULL CHECK (order_status IN ('COMPLETED', 'PENDING', 'CANCELLED', 'REFUNDED')),
    created_at timestamptz NOT NULL
);

CREATE TABLE order_lines (
    order_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id varchar(50) NOT NULL REFERENCES orders(order_id),
    product_id bigint NOT NULL REFERENCES products(product_id),
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(12, 2) NOT NULL CHECK (unit_price >= 0),
    UNIQUE (order_id, product_id)
);

CREATE TABLE transactions (
    transaction_id varchar(50) PRIMARY KEY,
    order_id varchar(50) NOT NULL REFERENCES orders(order_id),
    account_id varchar(50) NOT NULL REFERENCES accounts(account_id),
    amount numeric(15, 2) NOT NULL CHECK (amount >= 0),
    transaction_type varchar(20) NOT NULL CHECK (transaction_type IN ('PAYMENT', 'REFUND', 'TRANSFER', 'WITHDRAWAL', 'DEPOSIT')),
    location varchar(100) NOT NULL,
    device_id varchar(50) NOT NULL,
    occurred_at timestamptz NOT NULL
);
